### PR TITLE
an elegant implementation for Feature Aggregating.

### PR DESCRIPTION
**Pull request by guikunchen**
the code mentioned in https://github.com/ma-xu/Context-Cluster/issues/15

### CODE REVIEW

**Comment by guikunchen** [comment]
Not exactly equal, with an error of [min -> 0] [mean -> 1.1e-8] [max -> 7.6e-6]

**Comment by ma-xu** [comment]
@guikunchen Thanks a lot for your great contributions! I will look into it and train a model by Sep 10. And I will merge it, many thanks! :heart:

**Comment by guikunchen** [comment]
After a careful check, it's not a right implementation :(

**Comment by guikunchen** [comment]
After a careful check, I found that it's not a right implementation :(

**Pull request closed without merging**
